name: Run Selenium Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
        options: >-
          --shm-size 2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Selenium Tests
        run: mvn test

		- name: Find latest Extent Report
		  id: find_report
		  run: |
		    latest_report=$(ls -t test-output/ExtentReport_*.html | head -n 1)
		    echo "report_path=$latest_report" >> $GITHUB_OUTPUT

		- name: Upload Extent Report to GitHub Artifacts
		  uses: actions/upload-artifact@v4
		  with:
		    name: ExtentReport
		    path: ${{ steps.find_report.outputs.report_path }}

			body: |
			  Hello team,

			  ✅ The Selenium test run has completed.
			  📄 You can download the test report here:
			  🔗 https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

			  Go to the "Artifacts" section on the right to download the ExtentReport.

			  Regards,  
			  GitHub Actions

          to: patelharish304@gmail.com,harishpatel6260@gmail.com,harishpatel8364@gmail.com
          from: GitHub Actions <${{ secrets.EMAIL_USER }}>
          attachments: ${{ steps.find_report.outputs.report_path }}
