name: Run Selenium Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
        options: >-
          --shm-size 2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Selenium Tests
        run: mvn test

      # ✅ NEW STEP: Find Latest Extent Report
      - name: Find latest ExtentReport HTML
        id: find_report
        run: |
          latest_report=$(ls -t test-output/ExtentReport_*.html | head -n 1)
          echo "report_path=$latest_report" >> "$GITHUB_OUTPUT"

      # ✅ MODIFIED: Attach ExtentReport to email
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "🧪 Selenium Build ${{ job.status }}"
          body: |
            Hello team,

            The Selenium test run has completed.
            ✅ Status: ${{ job.status }}
            🔗 Workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            📎 The ExtentReport is attached to this email.

            Regards,  
            GitHub Actions
          to: patelharish304@gmail.com,harishpatel6260@gmail.com,harishpatel8364@gmail.com
          from: GitHub Actions <${{ secrets.EMAIL_USER }}>
          attachments: ${{ steps.find_report.outputs.report_path }}
